untested-text: "Untested" # used in placeholder

# /tiers command
player-no-exist: "&cThat player doesn't exist."
player-isnt-tested: "&cThat player is not tested on %site%." # %site% = site name
format-title: # %player% = target name, %points% = total points, %overall% = overall, %region% = region
  - "&6%player%'s Tiers"
  - "&cPoints: &f%points%"
  - "&bOverall: &f%overall%"
  - "&aRegion: &f%region%"

peaked-format: " &7(peaked %tier%&7)" # %tier%

colors: # colors for tiers when displayed on tier tagger or command, can use &a color codes or &#hexhex
  "HT1": "&6"
  "LT1": "&6"
  "HT2": "&6"
  "LT2": "&6"
  "HT3": "&6"
  "LT3": "&6"
  "HT4": "&6"
  "LT4": "&6"
  "HT5": "&6"
  "LT5": "&6"
  "vanilla": "&f"
  "sword": "&f"
  "uhc": "&f"
  "pot": "&f"
  "nethop": "&f"
  "smp": "&f"
  "axe": "&f"
  "creeper": "&f"
  "bow": "&f"
  "manhunt": "&f"
  "og_vanilla": "&f"
  "bed": "&f"
  "minecart": "&f"
  "mace": "&f"
  "speed": "&f"
  "iron_pot": "&f"
  "dia_smp": "&f"
  "dia_crystal": "&f"
  "elytra": "&f"
  "trident": "&f"
  "debuff": "&f"
  cart: "&f"
  crystal: "&f"
  diamondPot: "&f"
  diamondSmp: "&f"
  netheritePot: "&f"
  neth_pot: "&f"
