name: TierTagger
version: '1.2.0'
main: themasterkitty.tiertagger.TierTagger
api-version: '1.21'
authors: [ TheMasterKitty ]
softdepend: [ PlaceholderAPI ]
folia-supported: true

commands:
  tiers:
    description: "Get a player's tiers"
    usage: "§cUsage: /tiers <player> (site)"