name: TierTagger
version: '1.0.0'
main: themasterkitty.tiertagger.TierTagger
api-version: '1.21'
authors: [ TheMasterKitty ]
softdepend: [ PlaceholderAPI ]

commands:
  tiers:
    description: "Get a player's tiers"
    usage: "§cUsage: /tiers <player> (mctiers/subtiers)"